### ISSUE TITLE
login

### ISSUE THREAD

**Issue by Devli12** [Devli12/Arteshop#1]
one of the feature is not taking input to the database.

**Comment by rcampbell95** [comment]
Progress update:

Now when signing up no message shows up. The message in the picture below is a message I put in for debugging to check if the code was progressing. It validates the fields, validates the email, and then something happens when calling this method

// Register user

    this.authService.registerUser(user).subscribe(data => {
      if(data.success){
        this.flashMessage.show('You are now registered and can log in', {cssClass: 'alert-success', timeout: 3000});
        this.router.navigate(['/login']);
      } else {
        this.flashMessage.show('Something went wrong', {cssClass: 'alert-danger', timeout: 3000});
        this.router.navigate(['/register']);
      }
    });

in the file register.component.ts

![login_bug_progress](https://user-images.githubusercontent.com/4894794/33465776-854316a4-d5fe-11e7-82a4-fbabde990b9d.PNG)

**Comment by rcampbell95** [comment]
The problem now is that the data doesn't get saved to the database. Since this problem is fixed though, I can close this issue and open another one.
